#/etc/nginx/sites-available/site

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Pour les gros fichiers
        client_max_body_size 400M;

        server_name _ eleves.rezal-mdm.com eleves.mines-paris.eu;

        location /api {
                proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
                proxy_set_header Host               $host;
                proxy_set_header X-Real-IP          $remote_addr;
                proxy_set_header X-Forwarded-Scheme $scheme;
                proxy_set_header X-Forwarded-Proto  $scheme;
                proxy_set_header X-Forwarded-Host   $host;
                proxy_set_header X-Forwarded-Port   $server_port;

                proxy_pass http://backend:5001;
        }

        location /socket.io {
                proxy_buffering off;
                proxy_cache off;
                proxy_read_timeout 86400;
                proxy_send_timeout 86400;

                proxy_set_header X-Accel-Buffering no;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_pass http://backend:5001;
        }

        location /upload {
                alias /app/upload;
        }

        root /usr/share/nginx/html;
        index index.html;

        location / {
                try_files $uri $uri/ /index.html;
        }

        location /public/ {
                alias /var/www/html/;
                index index.php;
                try_files $uri $uri/ /public/index.php?$query_string;

                fastcgi_param HTTPS off;
                fastcgi_param HTTP_X_FORWARDED_PROTO http;
                fastcgi_param SERVER_PORT 8000;

                location ~ ^/public/(.+\.php)$ {
                        fastcgi_pass php:9000;
                        include fastcgi_params;
                        fastcgi_param SCRIPT_FILENAME /var/www/html/$1;
                }
        }
        location /public {
                return 301 $scheme://$host:8000/public/index.php;
        }
}

server {
        listen 80;
        listen [::]:80;

        server_name mines-paris.eu;

        root /home/rezal/site/public;
        index index.php;

        location / {
                try_files $uri /index.php;
        }
}
