name: site
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - Flask
  - Flask-SQLAlchemy
  - Flask-Login
  - Flask-Cors
  - Flask-SocketIO
  - Flask-Apscheduler
  - pytest
  - requests
  - eventlet
  - redis-py
  - pdf2image
  - pymysql
  - mariadb